USE BEM_T;

DROP TABLE ENDE;
DROP TABLE FACE;

CREATE TABLE FACE (
    FACE_ID INT NOT NULL,
    LOC VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TEL INT NOT NULL,
    PER INT NOT NULL,
    ATV boolean NOT NULL,
	PRIMARY KEY(FACE_ID)
);

CREATE TABLE ENDE (
    ENDE_ID INT NOT NULL,
    LOG VARCHAR(255) NOT NULL,
    BAI VARCHAR(255) NOT NULL,
    UF VARCHAR(255) NOT NULL ,
    CEP VARCHAR(255) NOT NULL ,
	FOREIGN KEY (ENDE_ID) REFERENCES FACE(FACE_ID)
);

